# User config
email: "dhammacharts@protonmail.com"
author: "DhammaCharts"
keywords: "Dhamma, Chart"
email: "dhammacharts@protonmail.com"

# Site config
# baseurl: "https://www.dhammacharts.org/old-website"
baseurl: 
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Config file
base_url: /
collections_dir: vault/content
data_dir: vault/data

# The collections represent the areas of the websites.
# Add collections below if you add a new _collection folder into content[:w
collections:
  charts:
    output: true
    sort_by: order
  3d-printing:
    output: true
    sort_by: order
  writtings:
    output: true
    sort_by: order
  references:
    output: true
    sort_by: order

# This will add default layout to all items into categories.
# For pages, make sure to specify a layout in the frontmatter
defaults:
  - scope:
      path: ""
      type: "charts"
    values:
      layout: "item"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: 
  - README.md
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - script/
  - vault/
