name: Process Images

on:
  workflow_dispatch:

jobs:
  process-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install vips
        run: sudo apt-get update && sudo apt-get install -y libvips

      - name: Run image processor
        run: bash ./scripts/process-images.sh
