name: Sync Vault to Jekyll

on:
  push:
    branches: [main]  # or your default branch

jobs:
  sync-and-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Vault Repo
        uses: actions/checkout@v3

      - name: Set Git Config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Clone Jekyll Website Repo
        env:
          PAT: ${{ secrets.JEKYLL_REPO_PAT }}
        run: |
          git clone https://x-access-token:${PAT}@github.com/YOUR_USERNAME/jekyll-site-repo.git
          mv jekyll-site-repo jekyll

      - name: Sync Vault Content into Jekyll Repo
        run: |
          rsync -av --delete --exclude=".git" --exclude="jekyll" ./ jekyll/content/

      - name: Run Image Processing Script
        run: |
          chmod +x ./scripts/process-images.sh
          ./scripts/process-images.sh jekyll/content/assets/images jekyll/assets

      - name: Commit and Push Changes to Jekyll Repo
        run: |
          cd jekyll
          git add .
          git commit -m "Sync from vault and update processed assets" || echo "No changes to commit"
          git push origin main
