name: Generate Assets

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allow manual run

jobs:
  generate-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Allows git push using GITHUB_TOKEN

      - name: Install VIPS
        run: sudo apt-get update && sudo apt-get install -y libvips-tools

      - name: Install yq
        run: sudo snap install yq

      - name: Make script executable
        run: chmod +x scripts/generate_assets.sh

      - name: Generate thumbnails and tiles
        run: ./scripts/generate_assets.sh

      - name: Commit and push generated assets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage and commit images
          git add -f assets/images/
          git commit -m "Update generated assets" || echo "No changes to commit"
          git push origin master

      - name: Cleanup committed assets
        if: always()
        run: |
          git rm -r --cached assets/images/
          git commit -m "Cleanup: remove temp generated assets" || echo "Nothing to clean"
          git push origin master
