name: Deploy Site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'gh-pages') || contains(github.event.head_commit.message, 'cf-pages')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Jekyll and Bundler
        run: |
          gem install jekyll bundler

      - name: Generate assets
        run: |
          chmod +x scripts/generate_assets.sh
          ./scripts/generate_assets.sh

      - name: Build Jekyll site
        run: |
          jekyll build --config _config.yml,_config-${{ contains(github.event.head_commit.message, 'cf-pages') && 'cdn' || 'gh' }}.yml

      - name: Deploy to GitHub Pages
        if: contains(github.event.head_commit.message, 'gh-pages')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

      - name: Push to cf-pages branch
        if: contains(github.event.head_commit.message, 'cf-pages')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git switch --orphan cf-pages
          git rm -rf .
          cp -r _site/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy to cf-pages"
          git push -f origin cf-pages
